### ISSUE TITLE
Free Api Disabled

### ISSUE THREAD

**Issue by keyreel** [jailsonsb2/RadioPlayer#14]
That's all? Is it possible to make it working? 
![2024-11-07](https://github.com/user-attachments/assets/ee64ccca-0f18-4958-9ae8-22b55c6aab04)

**Comment by jailsonsb2** [comment]
Hello! Due to increased demand for the service, we are migrating to new servers. To ensure that we can continue to provide a stable and high-quality experience, we are accepting voluntary contributions from those who are able to help.

If you are unable to contribute, please let us know. In that case, I will share an open server that you can use for free, but there is a risk that it may go offline due to high usage.

Thank you for your support and understanding!

**Comment by keyreel** [comment]
Hello. We are non-profit free internet-radio, all that we can pay are donations from our listeners and my own payments. Can you tell me what a reasonable donation amount would be acceptable?

**Comment by jailsonsb2** [comment]
I enabled the free option again but as I explained, I can't guarantee that it won't be overloaded, the value is any amount you can, it will be fully reversed to the payment of hosting/vps. Those who contribute will be moved there and will receive a unique link. You can use the free API and prepare to migrate to the paid API in the future.

**Comment by keyreel** [comment]
Thank you!
